// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "eventcontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CEventControl

IMPLEMENT_DYNCREATE(CEventControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CEventControl properties

/////////////////////////////////////////////////////////////////////////////
// CEventControl operations

void CEventControl::TestMethod()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
