#if !defined(AFX_EVENTCONTROL_H__110F3EEA_0EDE_4782_A8B3_B83FE84FF935__INCLUDED_)
#define AFX_EVENTCONTROL_H__110F3EEA_0EDE_4782_A8B3_B83FE84FF935__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEventControl wrapper class

class CEventControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CEventControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7ce7c2b3, 0x122d, 0x4343, { 0x8c, 0x18, 0xf1, 0x54, 0xdf, 0x4, 0x91, 0x6b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void TestMethod();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EVENTCONTROL_H__110F3EEA_0EDE_4782_A8B3_B83FE84FF935__INCLUDED_)
