// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "eventcontrol1.h"

/////////////////////////////////////////////////////////////////////////////
// CEventControl1

IMPLEMENT_DYNCREATE(CEventControl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CEventControl1 properties

/////////////////////////////////////////////////////////////////////////////
// CEventControl1 operations

void CEventControl1::TestMethod()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
