// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "p2i32ctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CP2i32ctrl1

IMPLEMENT_DYNCREATE(CP2i32ctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CP2i32ctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CP2i32ctrl1 operations
