#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CP2i32ctrl1 wrapper class

class CP2i32ctrl1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CP2i32ctrl1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4FC18FA3, 0xE7FC, 0x11D0, { 0x84, 0x1D, 0x0, 0xA0, 0xC9, 0x1F, 0x82, 0xB5 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:
enum
{
    DCX = 11,
    TIFFT4_G31D = 4,
    TIFFT4_G32D = 6,
    TIF_G41D = 5,
    PCX = 10,
    TIF_GAMMA_G31D = 19,
    TIF_GAMMA_G32D = 20,
    TIFFT6_G41D = 21,
    TIF_HUFFMAN = 8,
    TIFFT4_G31D_IF = 13,
    TIFFT4_G32D_IF = 15,
    TIFFT6_G41D_IF = 14,
    PNG = 51
}FileFormatConstants;


// Operations
public:

// _DPnxP2i

// Functions
//


// Properties
//

long GetFileFormat()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}
void SetFileFormat(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}
BOOL GetRenameSinglePage()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}
void SetRenameSinglePage(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}
BOOL GetSinglePageCountFrom1()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}
void SetSinglePageCountFrom1(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}
CString GetSinglePageMask()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}
void SetSinglePageMask(CString propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}
BOOL GetUseCustomLength()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}
void SetUseCustomLength(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}
short GetCustomPixelLength()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}
void SetCustomPixelLength(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}
BOOL GetUseCustomWidth()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}
void SetUseCustomWidth(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}
short GetCustomPixelWidth()
{
	short result;
	GetProperty(0x8, VT_I2, (void*)&result);
	return result;
}
void SetCustomPixelWidth(short propVal)
{
	SetProperty(0x8, VT_I2, propVal);
}
BOOL GetUseSkipFromTop()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}
void SetUseSkipFromTop(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}
short GetSkipTopPixels()
{
	short result;
	GetProperty(0xa, VT_I2, (void*)&result);
	return result;
}
void SetSkipTopPixels(short propVal)
{
	SetProperty(0xa, VT_I2, propVal);
}
BOOL GetUseAutoFileName()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}
void SetUseAutoFileName(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}
CString GetAutoFileName()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}
void SetAutoFileName(CString propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}
BOOL GetUseImageOverlay()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}
void SetUseImageOverlay(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}
BOOL GetImageOverlayStretchToFit()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}
void SetImageOverlayStretchToFit(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}
short GetImageOverlayAllPages()
{
	short result;
	GetProperty(0xf, VT_I2, (void*)&result);
	return result;
}
void SetImageOverlayAllPages(short propVal)
{
	SetProperty(0xf, VT_I2, propVal);
}
CString GetImageOverlayFileLandscape()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}
void SetImageOverlayFileLandscape(CString propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}
CString GetImageOverlayFilePortrait()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}
void SetImageOverlayFilePortrait(CString propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}
CString GetLastFileName()
{
	CString result;
	GetProperty(0x12, VT_BSTR, (void*)&result);
	return result;
}
void SetLastFileName(CString propVal)
{
	SetProperty(0x12, VT_BSTR, propVal);
}
short GetLastFileNumPages()
{
	short result;
	GetProperty(0x13, VT_I2, (void*)&result);
	return result;
}
void SetLastFileNumPages(short propVal)
{
	SetProperty(0x13, VT_I2, propVal);
}
CString GetLastFileSource()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}
void SetLastFileSource(CString propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}
short GetLastFileFormat()
{
	short result;
	GetProperty(0x15, VT_I2, (void*)&result);
	return result;
}
void SetLastFileFormat(short propVal)
{
	SetProperty(0x15, VT_I2, propVal);
}
CString GetLastDirectory()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}
void SetLastDirectory(CString propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}


};
