#if !defined(AFX_TEXTTOSPEECH_H__EB1EA09F_D1B9_4143_994E_839523861CE0__INCLUDED_)
#define AFX_TEXTTOSPEECH_H__EB1EA09F_D1B9_4143_994E_839523861CE0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTextToSpeech wrapper class

class CTextToSpeech : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTextToSpeech)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2398e32f, 0x5c6e, 0x11d1, { 0x8c, 0x65, 0x0, 0x60, 0x8, 0x18, 0x41, 0xde } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetInitialized();
	void SetInitialized(long nNewValue);
	void Speak(LPCTSTR Text);
	void StopSpeaking();
	void FastForward();
	void Pause();
	void Resume();
	void Rewind();
	long GetDevice();
	void SetDevice(long nNewValue);
	long GetEnabled();
	void SetEnabled(long nNewValue);
	long GetIsSpeaking();
	long GetSpeed();
	void SetSpeed(long nNewValue);
	CString GetTTSMode();
	void SetTTSMode(LPCTSTR lpszNewValue);
	void AboutDlg(long hWnd, LPCTSTR title);
	void GeneralDlg(long hWnd, LPCTSTR title);
	void LexiconDlg(long hWnd, LPCTSTR title);
	void TranslateDlg(long hWnd, LPCTSTR title);
	long GetFindEngine(LPCTSTR EngineId, LPCTSTR MfgName, LPCTSTR ProductName, LPCTSTR ModeID, LPCTSTR ModeName, long LanguageID, LPCTSTR dialect, LPCTSTR Speaker, LPCTSTR Style, long Gender, long Age, long Features, long Interfaces, 
		long EngineFeatures, long RankEngineID, long RankMfgName, long RankProductName, long RankModeID, long RankModeName, long RankLanguage, long RankDialect, long RankSpeaker, long RankStyle, long RankGender, long RankAge, long RankFeatures, 
		long RankInterfaces, long RankEngineFeatures);
	long GetCountEngines();
	CString ModeName(long index);
	CString MfgName(long index);
	CString ProductName(long index);
	CString ModeID(long index);
	CString Speaker(long index);
	CString Style(long index);
	long Gender(long index);
	long Age(long index);
	long Features(long index);
	long Interfaces(long index);
	long EngineFeatures(long index);
	long LanguageID(long index);
	CString dialect(long index);
	short GetMouthHeight();
	void SetMouthHeight(short nNewValue);
	short GetMouthWidth();
	void SetMouthWidth(short nNewValue);
	short GetMouthUpturn();
	void SetMouthUpturn(short nNewValue);
	short GetJawOpen();
	void SetJawOpen(short nNewValue);
	short GetTeethUpperVisible();
	void SetTeethUpperVisible(short nNewValue);
	short GetTeethLowerVisible();
	void SetTeethLowerVisible(short nNewValue);
	short GetTonguePosn();
	void SetTonguePosn(short nNewValue);
	short GetLipTension();
	void SetLipTension(short nNewValue);
	long GetLastError();
	void SetLastError(long nNewValue);
	short GetSuppressExceptions();
	void SetSuppressExceptions(short nNewValue);
	void Select(long index);
	short GetLipType();
	void SetLipType(short nNewValue);
	long GetCurrentMode();
	void SetCurrentMode(long nNewValue);
	long GetHWnd();
	long Find(LPCTSTR RankList);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEXTTOSPEECH_H__EB1EA09F_D1B9_4143_994E_839523861CE0__INCLUDED_)
