// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "crviewer1.h"

/////////////////////////////////////////////////////////////////////////////
// CCrviewer1

IMPLEMENT_DYNCREATE(CCrviewer1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCrviewer1 properties

/////////////////////////////////////////////////////////////////////////////
// CCrviewer1 operations
