#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCrviewer1 wrapper class

class CCrviewer1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCrviewer1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2DEF4530, 0x8CE6, 0x41C9, { 0x84, 0xB6, 0xA5, 0x45, 0x36, 0xC9, 0x2, 0x13 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:
enum
{
    crLoadingNothing = 0,
    crLoadingPages = 1,
    crLoadingTotaller = 2,
    crLoadingQueryInfo = 3
}CRLoadingType;
enum
{
    crDrillOnGroup = 0,
    crDrillOnGroupTree = 1,
    crDrillOnGraph = 2,
    crDrillOnMap = 3,
    crDrillOnSubreport = 4
}CRDrillType;
enum
{
    crDefaultCursor = 0,
    crArrowCursor = 1,
    crCrossCursor = 2,
    crIBeamCursor = 3,
    crNoCursor = 10,
    crWaitCursor = 11,
    crAppStartingCursor = 12,
    crHelpCursor = 13,
    crMagnifyCursor = 99
}CRTrackCursor;
enum
{
    crInt8 = 0,
    crInt16 = 1,
    crInt32 = 2,
    crNumber = 3,
    crCurrency = 4,
    crBoolean = 5,
    crDate = 6,
    crTime = 7,
    crDateTime = 8,
    crString = 9,
    crUnknownFieldType = 255
}CRFieldType;
enum
{
    crUnknownFieldDefType = 0,
    crDatabaseFieldType = 1,
    crOLAPDimensionFieldType = 2,
    crOLAPDataFieldType = 3,
    crOLAPCrossTabFieldType = 4,
    crFormulaFieldType = 5,
    crSummaryFieldType = 6,
    crSpecialVarFieldType = 7,
    crGroupNameFieldType = 8,
    crPromptingVarFieldType = 9,
    crText = 100,
    crOLEObject = 101,
    crSubreport = 102,
    crBitmap = 103,
    crBlob = 104,
    crLine = 105,
    crBox = 106,
    crGroupChart = 107,
    crCrosstabChart = 108,
    crDetailChart = 109,
    crCrossTab = 110,
    crGraphic = 111,
    crOOPSubreport = 112,
    crOLAPChart = 113,
    crGroupMap = 114,
    crCrosstabMap = 115,
    crDetailMap = 116,
    crOLAPMap = 117,
    crGroupHeaderSection = 200,
    crGroupFooterSection = 201,
    crDetailSection = 202,
    crReportHeaderSection = 203,
    crReportFooterSection = 204,
    crPageHeaderSection = 205,
    crPageFooterSection = 206
}CRObjectType;


// Operations
public:

// ICrystalReportViewer9

// Functions
//

	LPUNKNOWN get_ReportSource()
	{
		LPUNKNOWN result;
		InvokeHelper(0xfa, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, NULL);
		return result;
	}
	void put_ReportSource(LPUNKNOWN newValue)
	{
		static BYTE parms[] = VTS_UNKNOWN ;
		InvokeHelper(0xfa, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_DisplayGroupTree()
	{
		BOOL result;
		InvokeHelper(0xfb, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_DisplayGroupTree(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0xfb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_DisplayToolbar()
	{
		BOOL result;
		InvokeHelper(0xfc, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_DisplayToolbar(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0xfc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableGroupTree()
	{
		BOOL result;
		InvokeHelper(0xfd, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableGroupTree(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0xfd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableNavigationControls()
	{
		BOOL result;
		InvokeHelper(0xfe, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableNavigationControls(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0xfe, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableStopButton()
	{
		BOOL result;
		InvokeHelper(0xff, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableStopButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0xff, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnablePrintButton()
	{
		BOOL result;
		InvokeHelper(0x100, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnablePrintButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x100, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableZoomControl()
	{
		BOOL result;
		InvokeHelper(0x101, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableZoomControl(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x101, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableCloseButton()
	{
		BOOL result;
		InvokeHelper(0x102, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableCloseButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x102, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableProgressControl()
	{
		BOOL result;
		InvokeHelper(0x103, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableProgressControl(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x103, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableSearchControl()
	{
		BOOL result;
		InvokeHelper(0x104, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableSearchControl(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x104, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableRefreshButton()
	{
		BOOL result;
		InvokeHelper(0x105, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableRefreshButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x105, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableDrillDown()
	{
		BOOL result;
		InvokeHelper(0x106, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableDrillDown(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x106, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableAnimationCtrl()
	{
		BOOL result;
		InvokeHelper(0x107, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableAnimationCtrl(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x107, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableSelectExpertButton()
	{
		BOOL result;
		InvokeHelper(0x108, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableSelectExpertButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x108, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	void ViewReport()
	{
		InvokeHelper(0x109, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	BOOL get_EnableToolbar()
	{
		BOOL result;
		InvokeHelper(0x154, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableToolbar(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x154, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_DisplayBorder()
	{
		BOOL result;
		InvokeHelper(0x155, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_DisplayBorder(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x155, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_DisplayTabs()
	{
		BOOL result;
		InvokeHelper(0x156, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_DisplayTabs(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x156, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_DisplayBackgroundEdge()
	{
		BOOL result;
		InvokeHelper(0x157, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_DisplayBackgroundEdge(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x157, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	CString get_SelectionFormula()
	{
		CString result;
		InvokeHelper(0x158, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	void put_SelectionFormula(LPCTSTR newValue)
	{
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x158, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	LPDISPATCH get_TrackCursorInfo()
	{
		LPDISPATCH result;
		InvokeHelper(0x159, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
		return result;
	}
	short get_ActiveViewIndex()
	{
		short result;
		InvokeHelper(0x15a, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
		return result;
	}
	short get_ViewCount()
	{
		short result;
		InvokeHelper(0x15b, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
		return result;
	}
	void ActivateView(VARIANT Index)
	{
		static BYTE parms[] = VTS_VARIANT ;
		InvokeHelper(0x15c, DISPATCH_METHOD, VT_EMPTY, NULL, parms, &Index);
	}
	void AddView(VARIANT GroupPath)
	{
		static BYTE parms[] = VTS_VARIANT ;
		InvokeHelper(0x15d, DISPATCH_METHOD, VT_EMPTY, NULL, parms, &GroupPath);
	}
	void CloseView(VARIANT Index)
	{
		static BYTE parms[] = VTS_VARIANT ;
		InvokeHelper(0x15e, DISPATCH_METHOD, VT_EMPTY, NULL, parms, &Index);
	}
	VARIANT GetViewPath(short Index)
	{
		VARIANT result;
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x15f, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms, Index);
		return result;
	}
	void PrintReport()
	{
		InvokeHelper(0x160, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void Refresh()
	{
		InvokeHelper(0x161, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void SearchForText(LPCTSTR Text)
	{
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x162, DISPATCH_METHOD, VT_EMPTY, NULL, parms, Text);
	}
	void ShowFirstPage()
	{
		InvokeHelper(0x163, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void ShowNextPage()
	{
		InvokeHelper(0x164, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void ShowPreviousPage()
	{
		InvokeHelper(0x165, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void ShowLastPage()
	{
		InvokeHelper(0x166, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void ShowNthPage(short PageNumber)
	{
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x167, DISPATCH_METHOD, VT_EMPTY, NULL, parms, PageNumber);
	}
	void Zoom(short ZoomLevel)
	{
		static BYTE parms[] = VTS_I2 ;
		InvokeHelper(0x168, DISPATCH_METHOD, VT_EMPTY, NULL, parms, ZoomLevel);
	}
	long GetCurrentPageNumber()
	{
		long result;
		InvokeHelper(0x169, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	void ShowGroup(VARIANT GroupPath)
	{
		static BYTE parms[] = VTS_VARIANT ;
		InvokeHelper(0x16a, DISPATCH_METHOD, VT_EMPTY, NULL, parms, &GroupPath);
	}
	BOOL get_IsBusy()
	{
		BOOL result;
		InvokeHelper(0x16b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	BOOL get_EnablePopupMenu()
	{
		BOOL result;
		InvokeHelper(0x16c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnablePopupMenu(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x16c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableExportButton()
	{
		BOOL result;
		InvokeHelper(0x16d, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableExportButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x16d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	BOOL get_EnableSearchExpertButton()
	{
		BOOL result;
		InvokeHelper(0x16f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableSearchExpertButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x16f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	void SearchByFormula(LPCTSTR formula)
	{
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x170, DISPATCH_METHOD, VT_EMPTY, NULL, parms, formula);
	}
	CString GetViewName(BSTR * pTabName)
	{
		CString result;
		static BYTE parms[] = VTS_PBSTR ;
		InvokeHelper(0x171, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, pTabName);
		return result;
	}
	BOOL get_EnableHelpButton()
	{
		BOOL result;
		InvokeHelper(0x172, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_EnableHelpButton(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x172, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}
	VARIANT GetGroup()
	{
		VARIANT result;
		InvokeHelper(0x190, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
		return result;
	}
	void GetLastPageNumber(long * pageN, BOOL * lastPageKnown)
	{
		static BYTE parms[] = VTS_PI4 VTS_PBOOL ;
		InvokeHelper(0x191, DISPATCH_METHOD, VT_EMPTY, NULL, parms, pageN, lastPageKnown);
	}
	void RefreshEx(BOOL refreshServerData)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x192, DISPATCH_METHOD, VT_EMPTY, NULL, parms, refreshServerData);
	}
	BOOL get_LaunchHTTPHyperlinksInNewBrowser()
	{
		BOOL result;
		InvokeHelper(0x1f4, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
		return result;
	}
	void put_LaunchHTTPHyperlinksInNewBrowser(BOOL newValue)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x1f4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, newValue);
	}

// Properties
//



};
