// ATLSink.idl : IDL source for ATLSink.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLSink.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(F015929D-9EE4-485E-B4C1-632BA2B22143),
	version(1.0),
	helpstring("ATLSink 1.0 Type Library")
]
library ATLSINKLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
